[2024-07-15 17:36:33,523] 97 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2024-07-15 17:36:33,523] 97 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[2024-07-15 17:36:45,760] 1414 app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Data_science_projects\DS_emp_pred\emp-pred_end_to_end_pipeline\app.py", line 11, in home_page
    return render_template("index.html")
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[2024-07-15 17:36:45,764] 97 werkzeug - INFO - 127.0.0.1 - - [15/Jul/2024 17:36:45] "[35m[1mGET / HTTP/1.1[0m" 500 -
[2024-07-15 17:36:45,833] 1414 app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Data_science_projects\DS_emp_pred\emp-pred_end_to_end_pipeline\app.py", line 11, in home_page
    return render_template("index.html")
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[2024-07-15 17:36:45,834] 97 werkzeug - INFO - 127.0.0.1 - - [15/Jul/2024 17:36:45] "[35m[1mGET / HTTP/1.1[0m" 500 -
[2024-07-15 17:36:46,224] 97 werkzeug - INFO - 127.0.0.1 - - [15/Jul/2024 17:36:46] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
